//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TinTuc
    {
        [Display(Name = "Mã tin tức")]
        public int Id { get; set; }
        [Display(Name = "Tiêu đề")]
        public string TieuDe { get; set; }
        [Display(Name = "Tóm tắt")]
        public string TomTat { get; set; }
        [Display(Name = "Nội dung")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string NoiDung { get; set; }
        [AllowHtml]
        [Display(Name = "Ảnh bài viết")]
        public string Picture { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Display(Name = "Mã danh mục")]
        public Nullable<int> DanhMucId { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
